var carName = "Ford";
var carName2 ="Lamborghini";
var carName3 = "Chevy";
var carName4 = "Volkswagon";
var carName5 = "Mercedes-Benz";
var carName6 = "BMW";
var carName7 = "Honda";
var carName8 = "Porsche";
var carName9 = "Nissan";
var carName10 = "Acura";
var carName11 = "Alfa-Romeo";
var carName12 = "Aston-Martin";
var carName13 = "Audi";
var carName14 = "Bently";
var carName15 = "Cadillac";
var carName16 = "Bugatti";
var carName17 = "Buick";
var carName18 = "Ferrari";
var carName19 = "Chrysler";
var carName20 = "Fiat";

document.write(carName);
document.write(carName2);
document.write(carName3);
document.write(carName4);
document.write(carName5);
document.write(carName6);
document.write(carName7);
document.write(carName8);
document.write(carName9);
document.write(carName10);
document.write(carName11);
document.write(carName12);
document.write(carName13);
document.write(carName14);
document.write(carName15);
document.write(carName16);
document.write(carName17);
document.write(carName18);
document.write(carName19);
document.write(carName20);
